import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/shares/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen">
          <div className="h-16 bg-white flex items-center pl-4 sticky top-0">
            <header>
              <h1 className="text-xl font-bold text-sky-400">Todo app</h1>
            </header>
          </div>
          <div className="w-full h-auto flex">
              <Sidebar />
              <div className="main-content flex-grow">
                {children}
              </div>
          </div>
        </div>
      </body>
    </html>
  );
}
